POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTdiNWY3YTUzMGRlOTViMmU5ZTY1MCIsInVzZXJuYW1lIjoienlsb3duIiwiaWF0IjoxNzAwNDQ3NjU3LCJleHAiOjE3MDEwNTI0NTd9.aZhOC0GDNJ4pFZaYGBm2MB5eBsjLHTgHYvax_PoznlE

{
    "content": "Otra note con token",
    "important": true
}
  